creating an array

In [7]:
import numpy as np #importilng the numpy libray with alias name

In [9]:
#creating an array 
n1 = np.array([1,2,3])
print(n1)

[1 2 3]


In [11]:
#creating 2D Array
n2 = np.array([[1,2,3],[4,5,6]])
print(n2)

[[1 2 3]
 [4 5 6]]


In [13]:
#zero's filled in 2D Arrays
n3 = np.zeros([2,3], dtype = 'int32') #[first enter the number of rows, no of columns] dtype --> datatype
print(n3)

[[0 0 0]
 [0 0 0]]


In [15]:
#array filled with 1's
n4 = np.ones([2,3,3],dtype = 'int32') #(number of arrays, no of rows, no of columns)
print(n4)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [17]:
# create an empty array
n5 = np.empty([1,3])
print(n5)

[[1.09564483e-311 0.00000000e+000 2.18174307e+243]]


In [19]:
#creating an array with a range of values
n6 = np.arange(10)
print(n6)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
n7 = np.arange(-5,10,5) #(start value, stop value, step value) and always stop is n-1 i.e if 10 na it will stop only at 9
print(n7)

[-5  0  5]


In [23]:
#linear spaced entities
n8 = np.linspace(10,20,num = 3)
print(n8)

[10. 15. 20.]


In [25]:
# create an array with same number
n9 = np.full([2,3],100)
print(n9)

[[100 100 100]
 [100 100 100]]


In [27]:
# we already created an empty array and stored it in n5. You can even use that and fill the required number.
n5.fill(100)
print(n5)

[[100. 100. 100.]]


Access the array

In [30]:
print(n1[0])

1


In [32]:
print(n1[-1]) #backward indexing 😊

3


In [34]:
# accessing an element of 2D Array
print(n2[0,1]) #(first access the row number, then the column number)

2


In [36]:
print(n2[1,:]) # prints the entire row as output

[4 5 6]


In [38]:
print(n2[:,1])

[2 5]


In [40]:
n4[1,1,2] = 10 # changing the value to another value
print(n4)

[[[ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]]

 [[ 1  1  1]
  [ 1  1 10]
  [ 1  1  1]]]


Size and Shape

In [43]:
print(n4.ndim) # tells us how many dimensions or axes

3


In [45]:
print(n4.shape) # tells us the internal structure of the array

(2, 3, 3)


In [47]:
print(n4.size) #prints the tot no of elements

18


In [49]:
print(n4.dtype)

int32


In [51]:
print(n4.itemsize) # to store an each element we require 4 bytes of data

4


In [53]:
print(n4.nbytes) # total number of bytes is 18*4 = 72

72


Sorting an Array

In [56]:
n10 = np.array([1,2,5,4,3,6,5,4,10,23,12,13])
np.sort(n10) # built-in function available inn 

array([ 1,  2,  3,  4,  4,  5,  5,  6, 10, 12, 13, 23])

In [58]:
n11 = np.array([[3,2,1],[3,2,1]])
np.sort(n11)

array([[1, 2, 3],
       [1, 2, 3]])

In [60]:
np.sort(n11,axis=0) #takes first elemnt of the 1st and 2nd array and compares . if 1st<<2nd then it remains same . otherwise swapping occurs. continue the same to the next elements also

array([[3, 2, 1],
       [3, 2, 1]])

Reshaping and Array Conversions

In [63]:
n12 = n10.reshape(6,2)
print(n12)

[[ 1  2]
 [ 5  4]
 [ 3  6]
 [ 5  4]
 [10 23]
 [12 13]]


In [65]:
n13 = n10.reshape(2,6)
print(n13)

[[ 1  2  5  4  3  6]
 [ 5  4 10 23 12 13]]


In [67]:
n14 = np.arange(4)
print(n14)
n15 = np.arange(5,9)
print(n15)
n16 = np.concatenate((n14,n15))
print(n16)

[0 1 2 3]
[5 6 7 8]
[0 1 2 3 5 6 7 8]


In [73]:
n17 = np.arange(8)
print(n17)
n18 = n17[np.newaxis,:]
n19 = n17[:,np.newaxis]
print(n18)
print(n19)

[0 1 2 3 4 5 6 7]
[[0 1 2 3 4 5 6 7]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [79]:
n20 = np.expand_dims(n16,axis = 0) # axis = 1 print the output last above example
print(n20)

[[0 1 2 3 5 6 7 8]]


Indexing and slicing

In [82]:
n21 = np.arange(10)
print(n21)
print(n21[n21<5])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [90]:
print(n21[(n21>3) & (n21 < 8) ])

[4 5 6 7]


In [92]:
five_up = n21>5
print(five_up)
print(n21[five_up])

[False False False False False False  True  True  True  True]
[6 7 8 9]


stack, split


In [97]:
n22 = np. array([[1,2],[4,5]])
n23 = np.array([[3,4],[6,7]])
np.hstack((n22,n23)) # horizontal join

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [101]:
n22 = np. array([[1,2],[4,5]])
n23 = np.array([[3,4],[6,7]])
np.vstack((n22,n23)) # vertical join

array([[1, 2],
       [4, 5],
       [3, 4],
       [6, 7]])

In [105]:
n24 = np.arange(20)
np.hsplit(n24,4) # the variable to split, and how count to be splitted

[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19])]

In [107]:
n25 = n24 #shallow copy --> only the reference of the array is copied. so, if you change the value in one array the other also chanes.
n25[0] = 100
print(n25)
print(n24)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]


In [111]:
#deep copy
n26 = n24.copy()
print(n26)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]


In [113]:
print(n24)
print(n26)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]


Math operations


In [116]:
print(n24 + n25)

[200   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38]


In [118]:
print(n24.max())

100


In [124]:
print(n24.min())

1


Random Numbers

In [127]:
np.random.rand(3,3)

array([[0.50493352, 0.84859548, 0.05677348],
       [0.51924595, 0.06153579, 0.79154921],
       [0.22555015, 0.41758594, 0.67577597]])

In [133]:
np.random.randint(20,size = (4,3)) # (max number , size of the array)

array([[ 8,  1, 13],
       [13,  8, 12],
       [ 1,  0, 17],
       [ 5,  4, 13]])